[package]
name = "wasmer-bus-hello"
version = "1.0.0"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2021"
description = "WebAssembly Bus Hello World"
license = "MIT OR Apache-2.0"
keywords = [ "wasi", "wasm", "bus", "time" ]
repository = "https://github.com/wasmerio/ate"
readme = "README.md"

[features]
default = []

[dependencies]
wasmer-bus = { version = "^1", path = "../lib", default_features = false, features = [ "macros" ] }
tracing = { version = "^0.1", features = [ "log" ] }
serde = { version = "^1", features = ["derive"] }
tokio = { git = "https://github.com/john-sharratt/tokio.git", branch = "wasix", features = [ "rt", "rt-multi-thread", "sync", "macros" ], default_features = false }
async-trait = "^0.1"
