[workspace]
members = [
    "lib",
    "ateweb",
    "atefs",
    "atedb",
    "atessh",
    "atesess",
    "atenet",
    "auth",
    "crypto",
    "files",
    "wasm-bus",
    "wasm-bus-types",
    "wasm-bus-macros",
    "wasm-bus-fuse",
    "wasm-bus-reqwest",
    "wasm-bus-ws",
    "wasm-bus-process",
    "wasm-bus-time",
    "wasm-bus-tty",
    "wasm-bus-tok",
    "wasm-bus-hello",
    "wasm-bus-webgl",
    "wasm-bus-mio",
    "term-lib",
    "tokera",
    "mio-lib",
    "tokterm",
    "tokweb",
    "grammar",
]

[profile.release]
debug = 1
