[workspace]
members = [
    "lib",
    "ateweb",
    "atefs",
    "atedb",
    "atessh",
    "atesess",
    "auth",
    "files",
    "wasm-bus",
    "wasm-bus-types",
    "wasm-bus-macros",
    "wasm-bus-fuse",
    "wasm-bus-reqwest",
    "wasm-bus-ws",
    "wasm-bus-process",
    "wasm-bus-time",
    "wasm-bus-tty",
    "term-lib",
    "tokterm",
    "tokweb",
    "grammar",
]

[profile.release]
debug = 1
