[package]
name = "wasmer-bus-tty"
version = "1.2.1"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2021"
description = "WebAssembly Terminal Interface"
license = "MIT OR Apache-2.0"
keywords = [ "wasi", "wasm", "bus", "websocket" ]
repository = "https://github.com/wasmerio/ate"
readme = "README.md"

[features]
default = []
sys = [ "libc", "tokio/rt-multi-thread" ]

[dependencies]
tracing = { version = "^0.1", features = [ "log" ] }
serde = { version = "^1", features = ["derive"] }
url = "2"
async-trait = "^0.1"
wasmer-bus = { version = "^1", path = "../lib", default_features = false, features = [ "macros" ] }

[target.'cfg(target_family = "wasm")'.dependencies]
tokio = { version = "1.20.1", features = [ "sync", "macros" ], default_features = false }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
libc = { version = "0.2", optional = true }
tokio = { version = "1.20.1", features = [ "io-util", "macros", "sync" ], default_features = false }

[dev-dependencies]
tokio = { version = "1.20.1", features = [ "rt", "io-util", "macros", "sync" ], default_features = false }