[package]
name = "wasmer-bus-process"
version = "1.1.0"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2021"
description = "WebAssembly Process Interface"
license = "MIT OR Apache-2.0"
keywords = [ "wasi", "wasm", "bus", "process" ]
repository = "https://github.com/wasmerio/ate"
readme = "README.md"

[features]
default = []

[dependencies]
wasmer-bus = { version = "^1", path = "../lib", default_features = false, features = [ "macros" ] }
tracing = { version = "^0.1", features = [ "log" ] }
serde = { version = "^1", features = ["derive"] }
bytes = "1"
tokio = { version = "1.20.1", features = [ "sync", "macros" ], default_features = false }
async-trait = "^0.1"
dummy-waker = "^1"