[package]
name = "wasmer-bus-webgl"
version = "1.0.3"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2021"
description = "WebAssembly WebGL Interface"
license = "MIT OR Apache-2.0"
keywords = [ "wasi", "wasm", "opengl", "webgl" ]
repository = "https://github.com/wasmerio/ate"
readme = "README.md"

[features]
default = []
backend = []

[dependencies]
wasmer-bus = { version = "^1", path = "../lib", default_features = false, features = [ "macros" ] }
serde = { version = "^1", features = ["derive"] }
async-trait = "^0.1"
