[package]
name = "wasm-bus-types"
version = "1.0.0"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2018"
description = "WebAssembly Bus Macros"
license = "MIT OR Apache-2.0"
keywords = [ "wasi", "wasm", "bus" ]
repository = "https://github.com/john-sharratt/ate"
readme = "README.md"